import type { ModuleMeta } from "@/lib/types";

export const moduleMetas: ModuleMeta[] = [
  {
    slug: "01-bem-vindo-atlasgr",
    number: 1,
    title: "Bem-vindo à ATLASGR",
    shortDescription: "História, propósito, valores, cultura e organograma da empresa.",
    durationMinutes: 40,
    status: "ready",
    category: "Fundamentos",
    imageUrl: "/brand/module_banner.jpg",
    imageCaption: "Cultura organizacional e propósito ATLASGR",
  },
  {
    slug: "02-mercado-logistica",
    number: 2,
    title: "Mercado de Logística",
    shortDescription: "Supply chain, transportadoras, embarcadores e tipos de carga e operação.",
    durationMinutes: 35,
    status: "ready",
    category: "Fundamentos",
    imageUrl: "/brand/screenshots/connect_plus_motorista.png",
    imageCaption: "Fluxos e atores da cadeia logística",
  },
  {
    slug: "03-gerenciamento-risco",
    number: 3,
    title: "Gerenciamento de Risco",
    shortDescription: "Do conceito básico ao avançado: PGR, apólice, sinistro e o papel da Central.",
    durationMinutes: 55,
    status: "ready",
    category: "Fundamentos",
    imageUrl: "/brand/screenshots/newconnect_tela_alerta.png",
    imageCaption: "Camadas de prevenção, sinal e decisão",
  },
  {
    slug: "04-produtos-atlasgr",
    number: 4,
    title: "Produtos ATLASGR",
    shortDescription: "Visão geral do portfólio: gerenciamento de risco, tecnologia, perfil securitário e bases dedicadas.",
    durationMinutes: 45,
    status: "ready",
    category: "Soluções ATLASGR",
    imageUrl: "/brand/screenshots/newconnect-dashboard.png",
    imageCaption: "Cockpit operacional e ecossistema de soluções AtlasGR",
  },
  {
    slug: "05-software-logistico",
    number: 5,
    title: "Software Logístico — Sistema Atlas Connect",
    shortDescription: "Telas, funcionalidades e fluxo de trabalho do sistema Atlas Connect e Portal Atlas.",
    durationMinutes: 50,
    status: "ready",
    category: "Soluções ATLASGR",
    imageUrl: "/brand/screenshots/portalatlas-sm.png",
    imageCaption: "Visibilidade operacional, SM e regras do PGR no Atlas Connect",
  },
  {
    slug: "06-atlas-profile",
    number: 6,
    title: "Atlas Profile",
    shortDescription: "Background check, biometria e compliance na análise de motoristas e veículos.",
    durationMinutes: 35,
    status: "ready",
    category: "Soluções ATLASGR",
    imageUrl: "/brand/screenshots/perfil-securitario.png",
    imageCaption: "Consulta de Registros Recentes e decisão cadastral informada no Atlas Profile",
  },
  {
    slug: "07-integracoes",
    number: 7,
    title: "Integrações",
    shortDescription: "Como o Atlas Connect conversa com ERP, TMS e rastreadores de diferentes fabricantes.",
    durationMinutes: 30,
    status: "ready",
    category: "Soluções ATLASGR",
    imageUrl: "/brand/screenshots/connect_plus_sm.png",
    imageCaption: "Fluxo de dados entre sistemas e integrações",
  },
  {
    slug: "08-clientes",
    number: 8,
    title: "Clientes",
    shortDescription: "Perfis de cliente atendidos pela Atlas: transportadoras, embarcadores e segmentos.",
    durationMinutes: 30,
    status: "ready",
    category: "Mercado e clientes",
    imageUrl: "/brand/screenshots/connect_plus_principal.png",
    imageCaption: "Perfis de clientes e contexto operacional",
  },
  {
    slug: "09-processo-comercial",
    number: 9,
    title: "Processo Comercial",
    shortDescription: "ICP, persona, dores, objeções, diferenciais competitivos e argumentação.",
    durationMinutes: 40,
    status: "ready",
    category: "Mercado e clientes",
    imageUrl: "/brand/screenshots/newconnect_monitoramento_sm.png",
    imageCaption: "Pesquisa, descoberta, qualificação e handoff comercial",
  },
  {
    slug: "10-termos-tecnicos",
    number: 10,
    title: "Termos Técnicos",
    shortDescription: "Glossário consolidado com os termos usados no dia a dia da Central e do mercado.",
    durationMinutes: 30,
    status: "ready",
    category: "Excelência operacional",
    imageUrl: "/brand/screenshots/portalatlas-sm.png",
    imageCaption: "Termos técnicos traduzidos em significado operacional",
  },
  {
    slug: "11-operacao",
    number: 11,
    title: "Operação",
    shortDescription: "Fluxos, monitoramento, checklist, alertas e eventos do dia a dia da Central.",
    durationMinutes: 45,
    status: "ready",
    category: "Excelência operacional",
    imageUrl: "/brand/screenshots/newconnect_dashboard.png",
    imageCaption: "Priorização, evidência, comunicação e handoff",
  },
  {
    slug: "12-compliance",
    number: 12,
    title: "Compliance",
    shortDescription: "LGPD, segurança da informação, sigilo e boas práticas internas.",
    durationMinutes: 30,
    status: "ready",
    category: "Excelência operacional",
    imageUrl: "/brand/screenshots/perfil_securitario_recentes.png",
    imageCaption: "Privacidade, segurança da informação e rastreabilidade",
  },
  {
    slug: "13-tecnologia",
    number: 13,
    title: "Tecnologia",
    shortDescription: "IA, analytics e automações aplicadas ao gerenciamento de risco logístico.",
    durationMinutes: 35,
    status: "ready",
    category: "Excelência operacional",
    imageUrl: "/brand/screenshots/newconnect-dashboard.png",
    imageCaption: "Sensoriamento, conectividade, sistema e decisão",
  },
  {
    slug: "14-casos-reais",
    number: 14,
    title: "Casos Reais",
    shortDescription: "Cases, recuperações e resultados operacionais da Atlas.",
    durationMinutes: 30,
    status: "ready",
    category: "Excelência operacional",
    imageUrl: "/brand/screenshots/perfil_securitario_profile.png",
    imageCaption: "Aprendizagem estruturada a partir de casos",
  },
  {
    slug: "15-preparacao-final",
    number: 15,
    title: "Preparação Final",
    shortDescription: "Revisão geral de todo o conteúdo antes da prova final.",
    durationMinutes: 30,
    status: "ready",
    category: "Conclusão",
    imageUrl: "/brand/module_banner.jpg",
    imageCaption: "Síntese, aplicação e validação de domínio",
  },
];

export function getModuleMeta(slug: string): ModuleMeta | undefined {
  return moduleMetas.find((m) => m.slug === slug);
}
